version: '3.7'

services:
  dockerize:
    image: jwilder/dockerize
  db:
    image: postgres:11.1
    container_name: postgres-project-b
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=proj693B119
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql