version: '3.7'

services:
  #  postgres-project-b:
  #    image: postgres:11.1
  #    container_name: postgres-project-b
  #    environment:
  #      - POSTGRES_USER=postgrespostgres-project-b
  #      - POSTGRES_PASSWORD=proj693B119
  #      - POSTGRES_DB=postgres
  #    ports:
  #      - "5432:5432"
  #    volumes:
  #      - ./db:/var/lib/postgresql/data
  #      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  discovery-service:
    image: pb-discovery-service:0.0.1-SNAPSHOT
    container_name: discovery-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8761:8761"
    expose:
      - "8761"
  api-gateway:
    image: pb-api-gateway:0.0.1-SNAPSHOT
    container_name: api-gateway
    depends_on:
      - discovery-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8011:8011"
    expose:
      - "8011"
  configuration-server:
    image: pb-configuration-server:0.0.1-SNAPSHOT
    container_name: configuration-server
    depends_on:
      - discovery-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8888:8888"
    expose:
      - "8888"
  game-info-service:
    image: pb-game-info-service:0.0.1-SNAPSHOT
    container_name: game-info-service
    depends_on:
      - discovery-service
      - configuration-server
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    expose:
      - "8080"
  pinnacle-service:
    image: pinnacle-service:0.0.1-SNAPSHOT
    container_name: pinnacle-service
    depends_on:
      - discovery-service
      - configuration-server
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8082:8082"
    expose:
      - "8082"
  oddsportal-soccer-service:
    image: pb-oddsportal-soccer-service:0.0.1-SNAPSHOT
    container_name: oddsportal-soccer-service
    depends_on:
      - discovery-service
      - configuration-server
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8081:8081"
    expose:
      - "8081"
  project-b-telegram-bot:
    image: pb-telegram-bot:0.0.1-SNAPSHOT
    container_name: project-b-telegram-bot
    depends_on:
      - pinnacle-service
      - discovery-service
      - configuration-server
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8083:8083"
    expose:
      - "8083"